### ISSUE TITLE
Data Broker should connect directly to Kafka instead of ZK

### ISSUE THREAD

**Issue by ericbaum** [dojot/data-broker#14]
When opening a connection to kafka, the producer code does so by using the zookeeper address to obtain the kafka host address:

```typescript
constructor(host?: string, init?: () => void) {
    console.log('--- init producer');
    let kafkaHost = host ? host : config.kafka.zookeeper;
    let client = new kafka.Client(kafkaHost);
```

This must be changed to remove the dependency on zookeeper and access directly the kafka addresses as it is done on the consumer code.

**Comment by rascaraficci** [comment]
Done!
