### ISSUE TITLE
Remove admin library in favor of Admin client from node-rdkafka

### ISSUE THREAD

**Issue by giovannicuriel** [dojot/data-broker#38]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
It's more like an update than a feature.

* **What is the current behavior?**
Current implementation uses our own @dojot/adminkafka library to create topics. This was done because node-rdkafka (which is based on librdkakfa) did not implement at that time this feature. But now things changed :tada: : as [pointed out here](https://github.com/Blizzard/node-rdkafka#admin-client), there is an implementation for that :fireworks: . 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
It's way more desirable to use features from node-rdkafka than implementing on our own.

* **Please tell us about your environment:**
  

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by rascaraficci** [comment]
This service will become deprecated soon, and the service that will replace it will consider the aspects pointed out in this issue.
